# INSERT pattern for Simple SCKAN's simplified surround relation from UBERON using ilxtr:surrounds relation
# ro:surrounds is a relation used for tissue structures that surrounds some organs; inverse: an organ surrounded by some structre
# - September 2024
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX partOf: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX ilxtr: <http://uri.interlex.org/tgbugs/uris/readable/>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX RO: <http://purl.obolibrary.org/obo/RO_>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

INSERT { ?tissue_structure ilxtr:surrounds ?organ_structure }

# To Test with SELECT statement
# SELECT
# ?tissue_structure ?tissue_structure_label
# ?organ_structure ?organ_structure_label

WHERE
{
    ?tissue_structure rdfs:subClassOf* [rdf:type owl:Restriction ;
                                           owl:onProperty RO:0002221 ; # surrounds relation http://purl.obolibrary.org/obo/RO_0002221
                                           owl:someValuesFrom ?organ_structure].
    ## To test with SELECT statement
    # FILTER (?organ_structure_label = 'prostate gland')
    # ?tissue_structure rdfs:label ?tissue_structure_label. 
    # ?organ_structure rdfs:label ?organ_structure_label.
   
    FILTER (CONTAINS (str(?tissue_structure), 'UBERON_') || CONTAINS (str(?tissue_structure), 'ilx_'))
    FILTER (CONTAINS (str(?organ_structure), 'UBERON_') || CONTAINS (str(?organ_structure), 'ilx_'))
}